#! /bin/sh

xbacklight -set 100 &
# ~/.fehbg &
~/bin/wallpaper.sh ~/Pictures/wallpapers/Chrome_OS_Wallpapers_Late_2020/Element_by_Rutger_Paulusse/ &
#wicd-client --tray &
#lxqt-powermanagement &
setxkbmap -layout it &
numlockx &
syndaemon -K -t -R -i 2 -d &
#xautolock -time 10 -locker i3lock-wrapper -notify 30 -notifier "notify-send 'locking the system' '30 seconds before locking system.' --icon=dialog-warning" &
#compton --dbus --config ~/.config/compton.conf &
picom -b
#conky -c ~/.config/conky/qlocktwo.conkyrc &
xdg-user-dirs-update &


